### ISSUE TITLE
Issue with rrule detecting last day of month when months are specified

### ISSUE THREAD

**Issue by Dwisf** [ical4j/ical4j#39]
I build an RRULE as follows:

FREQ=MONTHLY;WKST=MO;INTERVAL=1;BYMONTH=2,3,9,10;BYMONTHDAY=28,29,30,31;BYSETPOS=-1

The intention for the above RRULE is to return the last day of month specified by the BYMONTH list. So in this case I expect the above rule to return the following:

Feb 28, 2015
Mar 31, 2015
Sep 30, 2015
Oct 31, 2015
Feb 29, 2015
... etc ...

So if I input July 1, 2015 as the starting date, then I will get Sep 30, 2015 as the next recurrence. I think this rule is correct as intended, by verifying it here: http://jkbrzt.github.io/rrule/

However, ical4j gives different result. I can see the candidate dates are calculated first resulting in the set similar to the following:
Feb 28, 2015
Mar 28, 2015
Mar 29, 2015
Mar 30, 2015
Mar 31, 2015
... etc...

This set is then the input to the BYSETPOS  evaluation, in this case -1, which results in the last occurrence in the set being returned, irrespective the starting date.

Can we confirm if this is an issue with iCal4j?

**Comment by benfortuna** [comment]
This is potentially fixed now as a result of PR #48.

**Comment by voronaam** [comment]
Actually, it is not fixed. After reading the RFC I am not sure what is the expected behaviour here. The problem is that there is one BYSETPOS and two others: BYMONTH and BYMONTHDAY. The author wanted BYSETPOS to apply to the BYMONTHDAY set, but in reality it gets applies to the overall list of candidate dates (selecting the last month in the list only). 

RFC has it this way:

```
   If multiple BYxxx rule parts are specified, then after evaluating the
   specified FREQ and INTERVAL rule parts, the BYxxx rule parts are
   applied to the current set of evaluated occurrences in the following
   order: BYMONTH, BYWEEKNO, BYYEARDAY, BYMONTHDAY, BYDAY, BYHOUR,
   BYMINUTE, BYSECOND and BYSETPOS; then COUNT and UNTIL are evaluated.
```

I think the issue here is that BYMONTH rule evaluator breaks out of the `FREQ=MONTHLY` bound.

**Comment by benfortuna** [comment]
Ok I think this is now working as expected with the latest refactor of recurrence implementation.

For example, using the above rule for period `20150101/20170101` I get:

```
20150228
20150331
20150930
20151031
20160229
20160331
20160930
20161031
```

**Comment by voronaam** [comment]
Thank you. We will run a set of tests on our side.
